<?php
$languages = [
    __("Interested?", 'site-core'),
    __("I help people and team worldwide. I can help you build your next digital product so fell to contact me. Sooner you write is better for both of us.", 'site-core'),
    __("Name", 'site-core'),
    __("e.g. John Doe", 'site-core'),
    __("Email", 'site-core'),
    __("e.g. hello@yoursite.com", 'site-core'),
    __("Phone", 'site-core'),
    __("e.g. +1 373 3783", 'site-core'),
    __("I'm interested in", 'site-core'),
    __("Tell me more about your goals", 'site-core'),
    __("Captcha", 'site-core'),
    __("Send", 'site-core'),
    __("Articles", 'site-core'),
    __("Home", 'site-core'),
    __("Want to work toegether and create an amazing products with me?", 'site-core'),
    __("Hire Me", 'site-core'),
    __("Let's", 'site-core'),
    __("connect!", 'site-core'),
    __("by Me alongside UXnDev", 'site-core'),
    __("Previous", 'site-core'),
    __("Next", 'site-core'),
    __("More articles", 'site-core'),
    __("Table of Contents", 'site-core'),
    __("No headings were found on this page.", 'site-core'),
    __("Top", 'site-core'),
    __("By", 'site-core'),
    __("On", 'site-core'),
    __("Share", 'site-core'),
    __("Dribbble", 'site-core'),
    __("Scroll Down", 'site-core'),
    __("Latest Post", 'site-core'),
    __("Subscribe Now", 'site-core'),
    __("Watch My Profile", 'site-core'),
    __("Enjoyed This Article?", 'site-core'),
    __("Join our community of 3 million people and get updated every week We have a lot more just for you! Lets join us now", 'site-core'),
    __('My Blog', 'site-core'),
    __('for you', 'site-core'),
    __('Latest Articles', 'site-core'),
    __('Clients', 'site-core'),
    __('talking', 'site-core'),
    __('People Say about me', 'site-core'),
    __('Satisfation Rate', 'site-core'),
    __('Repeat Order', 'site-core'),
    __('Google Review', 'site-core'),
    __('Hire Me', 'site-core'),
    __('Show case', 'site-core'),
    __('Discover', 'site-core'),
    __('how I work', 'site-core'),
    __('Project Category', 'site-core'),
    __('Short Description', 'site-core'),
    __('Client', 'site-core'),
    __('Download CV', 'site-core'),
    
    // Homepage
    __('Top rated at', 'site-core'),
    __('Making Ideas Shine', 'site-core'),
    __('Talented Developer', 'site-core'),
    __('Who Helps you', 'site-core'),
    __("Imagine a walking shit, always stays at home, people says introvert, father says oh, but perfect on mothers sight. Yeah I know it's not referring to my quality. But I believe I have a thing after all! It's love, for what I do.", 'site-core'),
    __('Awards', 'site-core'),
    __('Project Finished', 'site-core'),
    __('Years Experience', 'site-core'),
    __('Global Clients', 'site-core'),
    __('Get Started', 'site-core'),
    __('I want to introduce myself', 'site-core'),
    __('Professional', 'site-core'),
    __('Experienced', 'site-core'),
    __("I've got a strong background in UX/UI design, system architecture, and web development, and my mission is all about helping businesses create solutions that are not just functional but also a joy to use. Whether I'm diving into research, sketching out designs, or getting into the nitty-gritty of implementation, I'm committed to delivering quality that truly makes a difference. I believe when you love what you do, it shows in the work, and that's exactly what I aim for in every project.", 'site-core'),
    __('Hire Me', 'site-core'),
    __('What I Do', 'site-core'),
    __('My', 'site-core'),
    __('Skillset', 'site-core'),
    __('UX Research', 'site-core'),
    __('UX Design', 'site-core'),
    __('Wireframe', 'site-core'),
    __('System Design', 'site-core'),
    __('Development', 'site-core'),
    __('Optimization', 'site-core'),
    __('See Past Work', 'site-core'),
    __('My Journey & Track Record', 'site-core'),
    __('tons of', 'site-core'),
    __('Experiences', 'site-core'),
    __('Started Schooling', 'site-core'),
    __('Completed SSC', 'site-core'),
    __('Junior Designer', 'site-core'),
    __('Sr. Graphics Designer', 'site-core'),
    __('Junior developer', 'site-core'),
    __('A Founder', 'site-core'),
    __('Ah it was such time i first meet my school life from nursery,', 'site-core'),
    __('and then I finished my secondary school certification program.', 'site-core'),
    __('After a long studies period, I found my self interested in graphics.', 'site-core'),
    __('I then recognized as a senior designer on a well known press.', 'site-core'),
    __('Slowly I learned programing in PHP & JavaScript as a Junior', 'site-core'),
    __("At the very biggening of 25, I'm a founder, an author and an instructor", 'site-core'),
    __("Understanding user needs through research and analysis to create data-driven design solutions. Conducting surveys, interviews, and usability testing to gather insights that enhance user experience.", 'site-core'),
    __("Crafting intuitive and user-friendly interfaces by focusing on user behavior, accessibility, and aesthetics. Using wireframes, prototypes, and design systems to create seamless interactions.", 'site-core'),
    __("Developing structural blueprints for digital products, outlining key interface elements and user flows. Ensuring clarity and usability before diving into high-fidelity designs.", 'site-core'),
    __("Architecting scalable and efficient design systems to maintain consistency across platforms. Implementing reusable components and structured workflows to streamline development.", 'site-core'),
    __('Turning designs into functional products with clean, optimized, and maintainable code. Implementing front-end and back-end technologies to bring interactive experiences to life.', 'site-core'),
    __('Enhancing performance, accessibility, and usability through continuous testing and iteration. Fine-tuning design and code to ensure the best possible user experience.', 'site-core'),

    // Pricing
    __('Pricing', 'site-core'),
    __('Home', 'site-core'),
    __('Recommended', 'site-core'),
    __('Single', 'site-core'),
    __('All In one', 'site-core'),
    __('Only', 'site-core'),
    __('Start from', 'site-core'),
    __("It's not enough to get all of them at once, so it's a great place to start", 'site-core'),
    __('Suitable for those of you who do not have a team. Get all my service in single payment', 'site-core'),
    __('What will you get', 'site-core'),
    __('Order Now', 'site-core'),
    __('Brief draft', 'site-core'),
    __('Fast work', 'site-core'),
    __('3 revision for each service', 'site-core'),
    __('Source file deliverable', 'site-core'),
    __('6-month support', 'site-core'),
    __('UX & UI design', 'site-core'),
    __('System architecture', 'site-core'),
    __('Full development', 'site-core'),
    __('3 revisions for each service', 'site-core'),
    __('Performance & SEO optimization', 'site-core'),
    __('6-month support', 'site-core'),
    __('How I process', 'site-core'),
    __('your order', 'site-core'),
    __('Your create an order', 'site-core'),
    __("Once you submit your order, I'll review your project requirements in detail. You'll receive a confirmation and a quick follow-up to ensure I have all the information needed to start the work.", 'site-core'),
    __('Meet and Brief', 'site-core'),
    __("We'll schedule a meeting where we'll discuss your project goals, expectations, and any additional details that will help shape the final product. This is where we align our vision for the project.", 'site-core'),
    __("I execute and send you a result", 'site-core'),
    __("I will begin the execution phase, creating the design or development based on our discussions. Once the initial version is ready, I will send it over to you for review and feedback.", 'site-core'),
    __("Revision Until Finish The Work", 'site-core'),
    __("Based on your feedback, I'll make necessary revisions until we reach the perfect result. Your satisfaction is key, and I ensure the final product aligns with your expectations.", 'site-core'),

    // About Me
    __('UX Designer & Developer', 'site-core'),
    __('I craft experiences not just for my clients, but for the people who use them.', 'site-core'),
    __('Hire Me', 'site-core'),
    __('Download CV', 'site-core'),
    __('I want to introduce myself', 'site-core'),
    __("It's not only about", 'site-core'),
    __('the looks', 'site-core'),
    __('Define', 'site-core'),
    __('Low Fi', 'site-core'),
    __('Prototype', 'site-core'),
    __('Emphaty', 'site-core'),
    __('Skill in range', 'site-core'),
    __('measurable', 'site-core'),
    __('ability', 'site-core'),
    __('What App I Use', 'site-core'),
    __('mastered in 3 popular app for every designer', 'site-core'),
    __("I love software engineering and enjoy creating systems that actually work for people and that people love. You know how a song people love brings satisfaction to an artist? Yeah, that's how I feel about my work. I genuinely enjoy every step of the process, from brainstorming ideas to putting everything together. I really don't expect any business opportunities or to make a lot of money; I'm just looking for an opportunity to do something that makes my days fulfilling—something that keeps me focused on my work instead of worrying about other things.", 'site-core'),
    __('UX Research', 'site-core'),
    __('UX Design', 'site-core'),
    __('Wireframe', 'site-core'),
    __('System Design', 'site-core'),
    __('Development', 'site-core'),
    __('Optimization', 'site-core'),
    __('System Design', 'site-core'),
    __('System Design', 'site-core'),
    __('System Design', 'site-core'),
    __('Our Process', 'site-core'),

    // Contact Me
    __("I'm ready to help you", 'site-core'),
    __("Feel free to", 'site-core'),
    __("contact me", 'site-core'),
    __("How do I know if you're the right fit for my project?", 'site-core'),
    __("I specialize in both UX/UI design and full-stack development, building websites with WordPress, Shopify, Webflow, React, Next.js, PHP, and Node.js. If you need a seamless, high-performing digital product, I can bring your vision to life. Let's discuss your project to see if we're a great match!", 'site-core'),
    __("What do you need from me to get started?", 'site-core'),
    __("A clear idea of your goals, preferred design style (if any), and any reference websites or wireframes you have. Don't worry—if you're unsure, I'll guide you through the process!", 'site-core'),
    __("How long will my project take?", 'site-core'),
    __("Timelines depend on the project's complexity. A simple design or development task can take a few days, while a full website or app may take weeks. I'll provide an estimated timeframe after reviewing your requirements.", 'site-core'),
    __("Can you handle urgent projects?", 'site-core'),
    __("Yes! If you have a tight deadline, let me know. I offer expedited services for urgent projects, depending on availability.", 'site-core'),
    __("Contact me", 'site-core'),
    __("Message me on Linkedin", 'site-core'),

    // Portfolio
    __("I make digital products for your needs, and proudly I'll show you", 'site-core'),
    __("I have a good range of work experience, and it's from school project to venture backed business. My work also featured on NYTimes, and of course on out community contests. I believe if i found a little opportunity to work on, I try my best to make an attention.", 'site-core'),
    __("Let's start new project", 'site-core'),
    __("See my work", 'site-core'),
    __("Amazing Portfolio", 'site-core'),
    __("My latest", 'site-core'),
    __("cool project", 'site-core'),
    __("Project Name", 'site-core'),
    __("Showcase", 'site-core'),
    __("Google Review", 'site-core'),
    __("Repeat Order", 'site-core'),
    __("Satisfation Rate", 'site-core'),
    __("Happy customers", 'site-core'),
    __("customer smile is my breath", 'site-core'),
    __("of happiness", 'site-core'),
    __("Every sense of happiness and satisfaction that is born from customers becomes a value that is not comparable to anything. Trust is priceless", 'site-core'),
    __("Client Review", 'site-core'),

    // Faqs
    __("FAQs", 'site-core'),
    __("what can", 'site-core'),
    __("I help?", 'site-core'),
    __("Search...", 'site-core'),
    __("Why choose me for your project?", 'site-core'),
    __("I combine a passion for exceptional design with robust development expertise to deliver digital products that truly resonate. My comprehensive approach means your vision is transformed into a high-performing, visually engaging solution tailored to your business goals.", 'site-core'),
    __("What sets my services apart from others?", 'site-core'),
    __("With extensive experience in UX/UI design and full-stack development across platforms like WordPress, Shopify, Webflow, React, and more, I bring innovation and precision to every project. My commitment to staying ahead of industry trends ensures your project isn't just current—it's future-proof.", 'site-core'),
    __("How do I build lasting trust with my clients?", 'site-core'),
    __("Transparency, clear communication, and a proven track record define my client relationships. I keep you updated every step of the way and back my promises with tangible results, earning the confidence of businesses I work with time and again.", 'site-core'),
    __("How do I drive business success post-launch?", 'site-core'),
    __("I believe a great website is just the beginning. In partnership with two leading marketing agencies, I ensure your digital product achieves deep online visibility and growth. Together, we deploy targeted strategies that boost engagement and drive measurable business success.", 'site-core'),
    __("Common Questions", 'site-core'),
    __("Discover topics that my clients", 'site-core'),
    __("most ask", 'site-core'),
    __("Got questions? You're not alone! Here, I've answered some of the most common inquiries about my services, process, and expertise. Whether you're curious about project timelines, requirements, or how I work, you'll find the answers right here.", 'site-core'),
    __("Download My Profile", 'site-core'),
    __("Show Case", 'site-core'),
    __("How I process your request?", 'site-core'),
    __("How do you handle project inquiries?", 'site-core'),
    __("When you reach out with a project request, I take the time to understand your needs, goals, and vision. I'll review your requirements and schedule a consultation if needed. From there, I provide a tailored approach and suggest the best solutions for your project.", 'site-core'),
    __("What's your typical workflow once we start?", 'site-core'),
    __("How do you ensure quality and efficiency?", 'site-core'),
    __("I follow industry best practices in UX/UI design and full-stack development. By using structured workflows, modern tools, and iterative feedback, I ensure that every project meets high standards of usability, performance, and aesthetics.", 'site-core'),
    __("What if I need changes after the project is completed?", 'site-core'),
    __("I offer post-launch support and revisions based on the project agreement. If you need additional features or modifications beyond the initial scope, I'm happy to discuss an extended service plan or hourly updates to keep your project evolving.", 'site-core'),
    __("Want to work toegether and create an amazing products with me?", 'site-core'),

];



// [__ text=""]
